load /home/pmung/Dropbox/9_scripts/3_program/structures/4_Konformation/z_database/1ATP_E.pdb, templ
sele templ_resid, templ and poly and resi 122-138+162-183
load /home/pmung/scratch/newkinase2/4FVP_A.pdb, 4FVP_A
align 4FVP_A, templ_resid
save 4FVP_A.1atp.pdb, 4FVP_A
load /home/pmung/scratch/newkinase2/5DFZ_B.pdb, 5DFZ_B
align 5DFZ_B, templ_resid
save 5DFZ_B.1atp.pdb, 5DFZ_B
load /home/pmung/scratch/newkinase2/5MRB_A.pdb, 5MRB_A
align 5MRB_A, templ_resid
save 5MRB_A.1atp.pdb, 5MRB_A
load /home/pmung/scratch/newkinase2/5N7V_A.pdb, 5N7V_A
align 5N7V_A, templ_resid
save 5N7V_A.1atp.pdb, 5N7V_A
load /home/pmung/scratch/newkinase2/5N84_A.pdb, 5N84_A
align 5N84_A, templ_resid
save 5N84_A.1atp.pdb, 5N84_A
load /home/pmung/scratch/newkinase2/5N93_A.pdb, 5N93_A
align 5N93_A, templ_resid
save 5N93_A.1atp.pdb, 5N93_A
load /home/pmung/scratch/newkinase2/5NA0_A.pdb, 5NA0_A
align 5NA0_A, templ_resid
save 5NA0_A.1atp.pdb, 5NA0_A
load /home/pmung/scratch/newkinase2/5NTT_A.pdb, 5NTT_A
align 5NTT_A, templ_resid
save 5NTT_A.1atp.pdb, 5NTT_A
load /home/pmung/scratch/newkinase2/5O91_A.pdb, 5O91_A
align 5O91_A, templ_resid
save 5O91_A.1atp.pdb, 5O91_A
load /home/pmung/scratch/newkinase2/5TOB_A.pdb, 5TOB_A
align 5TOB_A, templ_resid
save 5TOB_A.1atp.pdb, 5TOB_A
load /home/pmung/scratch/newkinase2/5VAL_A.pdb, 5VAL_A
align 5VAL_A, templ_resid
save 5VAL_A.1atp.pdb, 5VAL_A
load /home/pmung/scratch/newkinase2/5VAM_A.pdb, 5VAM_A
align 5VAM_A, templ_resid
save 5VAM_A.1atp.pdb, 5VAM_A
load /home/pmung/scratch/newkinase2/5WIN_A.pdb, 5WIN_A
align 5WIN_A, templ_resid
save 5WIN_A.1atp.pdb, 5WIN_A
load /home/pmung/scratch/newkinase2/5X8I_A.pdb, 5X8I_A
align 5X8I_A, templ_resid
save 5X8I_A.1atp.pdb, 5X8I_A
load /home/pmung/scratch/newkinase2/5ZTN_A.pdb, 5ZTN_A
align 5ZTN_A, templ_resid
save 5ZTN_A.1atp.pdb, 5ZTN_A
load /home/pmung/scratch/newkinase2/6B4W_A.pdb, 6B4W_A
align 6B4W_A, templ_resid
save 6B4W_A.1atp.pdb, 6B4W_A
load /home/pmung/scratch/newkinase2/6BOD_A.pdb, 6BOD_A
align 6BOD_A, templ_resid
save 6BOD_A.1atp.pdb, 6BOD_A
load /home/pmung/scratch/newkinase2/6EIR_A.pdb, 6EIR_A
align 6EIR_A, templ_resid
save 6EIR_A.1atp.pdb, 6EIR_A
load /home/pmung/scratch/newkinase2/6EIS_A.pdb, 6EIS_A
align 6EIS_A, templ_resid
save 6EIS_A.1atp.pdb, 6EIS_A
load /home/pmung/scratch/newkinase2/6FT7_A.pdb, 6FT7_A
align 6FT7_A, templ_resid
save 6FT7_A.1atp.pdb, 6FT7_A
load /home/pmung/scratch/newkinase2/6FYI_A.pdb, 6FYI_A
align 6FYI_A, templ_resid
save 6FYI_A.1atp.pdb, 6FYI_A
load /home/pmung/scratch/newkinase2/6FYK_A.pdb, 6FYK_A
align 6FYK_A, templ_resid
save 6FYK_A.1atp.pdb, 6FYK_A
load /home/pmung/scratch/newkinase2/6FYP_A.pdb, 6FYP_A
align 6FYP_A, templ_resid
save 6FYP_A.1atp.pdb, 6FYP_A
load /home/pmung/scratch/newkinase2/6FYV_A.pdb, 6FYV_A
align 6FYV_A, templ_resid
save 6FYV_A.1atp.pdb, 6FYV_A
load /home/pmung/scratch/newkinase2/6G33_A.pdb, 6G33_A
align 6G33_A, templ_resid
save 6G33_A.1atp.pdb, 6G33_A
load /home/pmung/scratch/newkinase2/6GVJ_A.pdb, 6GVJ_A
align 6GVJ_A, templ_resid
save 6GVJ_A.1atp.pdb, 6GVJ_A
load /home/pmung/scratch/newkinase2/6H0O_A.pdb, 6H0O_A
align 6H0O_A, templ_resid
save 6H0O_A.1atp.pdb, 6H0O_A
load /home/pmung/scratch/newkinase2/6H3K_A.pdb, 6H3K_A
align 6H3K_A, templ_resid
save 6H3K_A.1atp.pdb, 6H3K_A
load /home/pmung/scratch/newkinase2/6HDP_A.pdb, 6HDP_A
align 6HDP_A, templ_resid
save 6HDP_A.1atp.pdb, 6HDP_A
load /home/pmung/scratch/newkinase2/6I5K_A.pdb, 6I5K_A
align 6I5K_A, templ_resid
save 6I5K_A.1atp.pdb, 6I5K_A
load /home/pmung/scratch/newkinase2/6I5L_A.pdb, 6I5L_A
align 6I5L_A, templ_resid
save 6I5L_A.1atp.pdb, 6I5L_A
load /home/pmung/scratch/newkinase2/6K0J_A.pdb, 6K0J_A
align 6K0J_A, templ_resid
save 6K0J_A.1atp.pdb, 6K0J_A
load /home/pmung/scratch/newkinase2/6N0P_A.pdb, 6N0P_A
align 6N0P_A, templ_resid
save 6N0P_A.1atp.pdb, 6N0P_A
load /home/pmung/scratch/newkinase2/6NSQ_A.pdb, 6NSQ_A
align 6NSQ_A, templ_resid
save 6NSQ_A.1atp.pdb, 6NSQ_A
load /home/pmung/scratch/newkinase2/6RCT_A.pdb, 6RCT_A
align 6RCT_A, templ_resid
save 6RCT_A.1atp.pdb, 6RCT_A
load /home/pmung/scratch/newkinase2/6U2G_B.pdb, 6U2G_B
align 6U2G_B, templ_resid
save 6U2G_B.1atp.pdb, 6U2G_B
hide everything
show ribbon
show lines, org
color white, all
color red, templ
center templ
save check_kinase.200227.1ATP_E.align.pse
